version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.9

jobs:
  build:
    docker:
      - image: 'circleci/node'
    steps:
      - checkout
      - run: sudo apt-get install python-dev
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -rf .git
      - run: rm -rf .circleci
      - run: rm -rf sass
      - aws-s3/sync:
          from: .
          to: 's3://leanmotherfuckers.com'
          arguments: --acl public-read --cache-control "max-age=86400"
          overwrite: true
